FROM php:8.2-fpm

ARG UID=1000
ARG GID=1000

RUN pecl install redis &&\
    docker-php-ext-enable redis

RUN apt-get update && apt-get install -y \
    git \
    curl \
    unzip \
    libzip-dev \
    libonig-dev

RUN docker-php-ext-install mbstring pdo_mysql zip

RUN groupadd -g $GID backend &&\
    useradd -u $UID -g backend -m backend

USER backend

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

CMD ['php-fpm']